version: '3'
services:
  streamlit_docker_app:
    image: streamlit_docker:latest
    build: .
    command: streamlit run app.py --server.port 8080
    ports:
    - 8080:8080
    volumes:
    - .:/app
    develop:
      watch:
        - path: .
          action: rebuild
        